"""Adding time index

Revision ID: 77fcc8db8790
Revises: 
Create Date: 2017-05-28 14:26:05.313882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fcc8db8790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('meteo',
    # sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('type', sa.String(), nullable=True),
    # sa.Column('value', sa.Float(), nullable=True)
    #  )
    op.create_index('meteo_time', 'meteo', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('meteo_time', table_name='meteo')
    # op.drop_table('meteo')
    # ### end Alembic commands ###
