"""Column to distinguish pre-aggregated columns

Revision ID: eac73fd76885
Revises: 77fcc8db8790
Create Date: 2017-05-28 14:54:24.206532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac73fd76885'
down_revision = '77fcc8db8790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo', sa.Column('preaggregated', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meteo', 'preaggregated')
    # ### end Alembic commands ###
